// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tesssuqemecqrffjogbt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRlc3NzdXFlbWVjcXJmZmpvZ2J0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2MzI2MzgsImV4cCI6MjA1OTIwODYzOH0.hVWYdTqigP1uHmKknS-92WWwXAUKCPzwUoqEG-_3Ijw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);